export const optionsKey = [
  { id: 1, name: "Visible part of page", selected: true },
  { id: 2, name: "Capture Fragment", selected: true },
  { id: 3, name: "Selected area", selected: true },
  { id: 4, name: "Select & Scroll", selected: true },
  { id: 5, name: "Entire page", selected: true },
  { id: 6, name: "Desktop screenshot", selected: true },
  { id: 7, name: "Hide the fixed elements", selected: true },
  { id: 8, name: "Display URL/date in Printing", selected: true },
  { id: 9, name: "Save the position of the selected area", selected: true },
  { id: 10, name: "Show in context menu", selected: true },
  { id: 11, name: "Show 'New' after app update", selected: true },
  { id: 12, name: "Auto-short URL after upload", selected: true },
  {
    id: 13,
    name: "Enable quick screenshot (without opening the menu)",
    selected: true,
  },
  { id: 14, name: "Start recording tab/page", selected: false },
  { id: 15, name: "Start recording desktop", selected: false },
  { id: 16, name: "Stop video recording", selected: false },
  { id: 17, name: "Pause/resume video recording", selected: false },
];
